ip = '0.0.0.0'
port = 8010
createdirs = false
altmainsite = [ "http://localhost:8010"]
file_tmp_path = "./temp"
file_path = 'server_files'
tauri_mode = false

[orgauth_config]
mainsite = 'http://localhost:8010'
appname = 'zknotes'
emaildomain = 'zknotes.com'
db = 'server.db'
admin_email = 'admin@bobadmin.com'
regen_login_tokens = true
# login_token_expiration_ms = 604800000
email_token_expiration_ms = 86400000
reset_token_expiration_ms = 86400000
invite_token_expiration_ms = 604800000
open_registration = true
send_emails = true
non_admin_invite = true
remote_registration = true
