ip = '0.0.0.0'
port = 8011
createdirs = true
altmainsite = [ "http://localhost:8011"]
file_tmp_path = "./clienttemp"
file_path = "./client_files"

[orgauth_config]
mainsite = 'http://localhost:8011'
appname = 'zknotes'
emaildomain = 'zknotes.com'
db = './client.db'
admin_email = 'admin@bo-bad-min.com'
regen_login_tokens = true
# login_token_expiration_ms = 604800000
email_token_expiration_ms = 86400000
reset_token_expiration_ms = 86400000
invite_token_expiration_ms = 604800000
open_registration = true
send_emails = true
non_admin_invite = true
remote_registration = true
