cargo watch -c \
  -w src \
  -w ../orgauth/rustlib/src/ \
  -w ../zkprotocol/src/ \
  -w Cargo.toml \
  -w ../zkprotocol/Cargo.toml \
  -w ../orgauth/rustlib/src/ \
  -w ../orgauth/rustlib/Cargo.toml \
  -w ../server-lib/src/ \
  -w ../server-lib/Cargo.toml \
  -x build -s ./client.sh
